### ISSUE TITLE
Lecture 01 - Homework:

### ISSUE THREAD

**Issue by deivid7007** [BaiGanio/PU-Intro-with-CSharp#23]
- [x]  Task1: Create project as in the video (link to Deivid youtube video)

- [x] Task2: Create "hello world" program

- [x] Task3: Calculate my age after X years. Use console input.

- [x] Task4: Age after 10 years/faculty number,round to 5 digit after decimal

**Comment by deivid7007** [comment]
Uploaded my version of AgeAfter10Years called TheUniqueNumber, I wish you like it.

**Comment by BaiGanio** [comment]
Here is missing one task which is the key point form task2 to task4.

**Comment by deivid7007** [comment]
Ok in progress right now.

**Comment by deivid7007** [comment]
Done
