### ISSUE TITLE
Task 2. Create task folders for each chapter from Course performance goals.docx

### ISSUE THREAD

**Issue by BaiGanio** [BaiGanio/PU-Intro-with-CSharp#5]
- [ ] Make sure the most course goals are grouped into tasks

- [ ] Tasks should be 8-10 as the number of exercises providing during the semester

- [ ] Each task should have homework folder which

- [ ] Each homework folder should consist of solution and .docx file with the task homework requirements.

**Comment by deivid7007** [comment]
Closed for now !
