### ISSUE TITLE
Compare Цели на курса, график и теми with Letcures C# folder till p5 - extract marked topics in the conversation

### ISSUE THREAD

**Issue by BaiGanio** [BaiGanio/PU-Intro-with-CSharp#81]
- Check can expand Цели на курса, график и теми with additional info from the .pptx
- Справка с учебника на Крушков

**Comment by Sunkatta** [comment]
Some ideas:

**Week 1**

- Include topic about algorithms and why are they useful in programming
- Include topic about what is Git, GitHub and the Powershell Console and how to work with them (basic Powershell commands, how to create a GitHub repository, etc.)

**Week 2**

- Build off of week 1 with more advanced stuff for GitHub (e.g. what are pull requests, issues perhaps or something else) 
- Each following week mention something new and interesting about GitHub (e.g. project boards for week 3, milestones for week 4, etc.)

**Week 4**

- Perhaps an exam preparation will be useful (revision of what was learned up until this point)
